name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        sudo apt-get install yarn
        yarn install
        yarn add robertnenciu/material-kit
        yarn run encore dev
        echo Add other actions to build,
        echo test, and deploy your project.
